CREATE TABLE IF NOT EXISTS listing
(
    id INTEGER PRIMARY KEY,
    url VARCHAR(255) NULL,
    created DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS chat
(
    id BIGINT PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    created DATETIME DEFAULT CURRENT_TIMESTAMP
);