CREATE TABLE IF NOT EXISTS listing
(
    id INTEGER PRIMARY KEY,
    url VARCHAR(255) NULL,
    created DATETIME DEFAULT CURRENT_TIMESTAMP,
    price VARCHAR(50) NULL,
    sq_footage VARCHAR(50) NULL,
    street VARCHAR(100) NULL,
    neighbourhood VARCHAR(100) NULL,
    location VARCHAR(100) NULL
);

CREATE TABLE IF NOT EXISTS chat
(
    id BIGINT PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    created DATETIME DEFAULT CURRENT_TIMESTAMP
);